### PR TITLE
Remove outdated self-cimports in pyx files and other Cython 3 prep

### PR DESCRIPTION
**Pull request by mkoeppe**
These self-imports from the pxd file are no longer needed (even in Cython 0.29.x).

Also replacing Python-2 style relative cimports with absolute cimports throughout.

### CODE REVIEW

**Comment by mkoeppe** [comment]
Which failures are you referring to? In the checks, the wheel build for PyPy 3.9 is failing, but I don't think it has anything to do with this PR.

**Comment by mkoeppe** [comment]
In https://github.com/sagemath/sage/pull/36439 I have the final missing piece for switching to Cython 3, but I've backed it out from this PR here to keep the scope limited.

**Comment by tkralphs** [comment]
> Which failures are you referring to? In the checks, the wheel build for PyPy 3.9 is failing, but I don't think it has anything to do with this PR.

OK, I didn't realize that it was the PyPy build that was failing, but yes, that's what I was referring to. Since that build looks to have been working up until this PR, I guessed it must be related. Perhaps that's not the case, but then should we should we either try to figure it out or remove that build before merging?

**Comment by mkoeppe** [comment]
Let's take that to:
- #180

**Comment by tkralphs** [comment]
Looking good now. Ready to merge?

**Comment by mkoeppe** [comment]
Yes, please go ahead

**Comment by mkoeppe** [comment]
As the next step, I will prepare a PR that switches from Cython < 3 to Cython >= 3

**Pull request merged**
